# Generated by Django 5.1.3 on 2024-11-21 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='formModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guideNumber', models.IntegerField()),
                ('guideName', models.CharField(max_length=50)),
                ('guideAddress', models.CharField(max_length=50)),
                ('guidePhoto', models.ImageField(upload_to='')),
                ('guideCertifiedDocument', models.ImageField(upload_to='')),
            ],
        ),
    ]
