# Generated by Django 5.1.3 on 2024-11-21 18:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0003_useraddress_userproduct_usertradition'),
    ]

    operations = [
        migrations.AddField(
            model_name='formmodel',
            name='guideEmail',
            field=models.EmailField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
