# Generated by Django 5.1.3 on 2024-11-21 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formmodel',
            name='guidePassword',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formmodel',
            name='guideReEnterPassword',
            field=models.CharField(default='temporary_password', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formmodel',
            name='guideUserName',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='formmodel',
            name='guideAddress',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='formmodel',
            name='guideCertifiedDocument',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='formmodel',
            name='guideName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='formmodel',
            name='guideNumber',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='formmodel',
            name='guidePhoto',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
