# Generated by Django 5.1.3 on 2024-11-22 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0005_product_service_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
