// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC77aYSW5F84QIVpTJZ40cRqixhOuSZkEU',
    appId: '1:1090978775476:web:22eae385c10808f44cf2e1',
    messagingSenderId: '1090978775476',
    projectId: 'safasughar',
    authDomain: 'safasughar.firebaseapp.com',
    storageBucket: 'safasughar.firebasestorage.app',
    measurementId: 'G-DNRXJPP8JW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZ8IyVf0RfU7T0q_nI8rfj43fso18FFVU',
    appId: '1:1090978775476:android:41b4c742ee4102ac4cf2e1',
    messagingSenderId: '1090978775476',
    projectId: 'safasughar',
    storageBucket: 'safasughar.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDk4vHUeTbY1Dy_Y3gM7e-S7RY1yXvnK60',
    appId: '1:1090978775476:ios:49cc9006ad17e8164cf2e1',
    messagingSenderId: '1090978775476',
    projectId: 'safasughar',
    storageBucket: 'safasughar.firebasestorage.app',
    iosBundleId: 'com.thaxaina.safasughar',
  );
}
